version: "3"

services:
  node-app:
    build: .
    image: node-app
    command: yarn run dev
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/backend-challenge-todo-list
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
